{
 "title": "OpenFaaS",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Functions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group by (function_name) (sum(gateway_service_count{}) without (timestamp)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests - 200 OK",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "scalar( sum( gateway_function_invocation_total {  code=\"200\"} ))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Functions list",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(gateway_service_count{}) without (timestamp)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Execution duration (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(rate(gateway_functions_seconds_sum[20s]) / rate(gateway_functions_seconds_count[20s])) ",
     "legendFormat": "{{function_name}} "
    }
   ]
  },
  {
   "title": "Replica scaling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    { "expr": "gateway_service_count", "legendFormat": "{{function_name}}" }
   ]
  },
  {
   "title": "Function rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "rate(gateway_function_invocation_total[20s])",
     "legendFormat": "{{function_name}}"
    }
   ]
  }
 ]
}